### ISSUE TITLE
Research docker/kubernetes

### ISSUE THREAD

**Issue by KentZeng123** [Husky-Coding-Project/algo-visualizer#11]
Research how docker/kubernetes can be used in our web app.

**Comment by AndrewZhang126** [comment]
https://azure.microsoft.com/en-us/topic/kubernetes-vs-docker/

Kupernetes can allow web server framework to operate in the cloud. Basically it allows us to deploy our web application onto the cloud instead of us having to work on a local application. AWS and Microsoft Azure (I think we have free subscriptions for Azure) offer Kupernetes support. In relation to Docker, while Docker helps deploy applications as containers that can run in the cloud, Kupernetes provides an API to manage these containers.
